#!/bin/sh

if [ -d "/sys/class/power_supply/BAT0" ]; then
		batt_state=$(cat /sys/class/power_supply/BAT0/status)
		batt_capacity=$(cat /sys/class/power_supply/BAT0/capacity)

		if [ ! "$batt_state" = "Charging" ]; then
				if [ "$batt_capacity" -lt 20 ]; then
						batt_icon="! "
				fi
		fi

		[ "$batt_state" = "Charging" ] && batt_icon="+ "
		batt="${batt_icon}$(cat /sys/class/power_supply/BAT0/capacity)"
		batt="${batt}%"

		echo "$batt"
fi
